### ISSUE TITLE
@console not functional with multiple active consoles

### ISSUE THREAD

**Issue by wkz** [troglobit/finit#103]
Specifying `tty @console` is supposed to bring up a getty on the active console. But when multiple consoles are active, no getty will be available on any of them.

This is because `/sys/class/tty/console/active` is assumed to only contain a single tty. When multiple consoles are active this files shows them all in a space separated list, e.g. `tty0 ttyAMA0`.

Fixing the parse error is easy. The hard question is: how to we handle this functionally? Do we spawn a getty for each console listed? Only the first?

**Comment by troglobit** [comment]
I think we need to start a getty on each one. That's the only thing that makes sense. The @console is special anyway, so having another exception for it should be OK.
