### ISSUE TITLE
Can't get service conditions & logging to work

### ISSUE THREAD

**Issue by villains** [troglobit/finit#104]
I'm using finit 3.1 to test out the new conditions and logging. I am using an IGEP Linux board with a very basic headless system.

I tried setting up a simple service that waits for syslogd to start (basically copy & pasted from the main `README.md`) but it doesn't seem to go.

Here is my `finit.conf` file:

```
user root
host igep00x0
runlevel 2

tty [12345] /dev/ttyO2 115200 nowait noclear linux

# Set up logging to /var/log/messages
log size=100k count=10
service [S12345] /sbin/syslogd -n -b 10 -D

service [2345] log <svc/sbin/syslogd> /bin/echo "Hello, world!"
```

Here is `/etc/fstab`:

```
tmpfs                /run                 tmpfs      defaults              0  0
tmpfs                /tmp                 tmpfs      defaults              0  0
```

After booting up, finit reports that the `syslogd` service started.

Finit reports the `echo` service as being `ready` which means it is missing conditions it needs to start. Listing the all the conditions shows that the `svc/sbin/syslogd` condition does not exist.

```
root@igep00x0:~# initctl show -v
1:1       running  414     [S12345----]  /sbin/syslogd -n -b 10 -D
2:1         ready  0       [--2345----]  /bin/echo "Hello, world!"
root@igep00x0:~# initctl cond dump
CONDITION                     STATUS
net/route/default             on
net/eth0/up                   on
net/eth0/exist                on
net/lo/running                on
net/lo/up                     on
net/lo/exist                  on
net/wlan0/exist               on
hook/sys/up                   on
hook/svc/up                   on
hook/net/up                   on
hook/mount/all                on
hook/mount/post               on
hook/mount/root               on
root@igep00x0:/run/finit/cond/hook# initctl cond show
PID     SERVICE               STATUS  CONDITION (+ ON, ~ FLUX, - OFF)
0       /bin/echo             off     <-svc/sbin/syslogd>
```

Am I doing something wrong? Please help :)

Thanks very much!

**Comment by villains** [comment]
Doh 🤦‍♂️ 

I didn't have the `pidfile` plugin installed. When I installed it, `svc/sbin/syslogd` appeared in the conditions. The output from `echo` did not appear in the log, and finit complained that it crashed too often, probably because it's not a real daemon.

When running a different program that is a real daemon, messages written to `stdout` and `stderr` appeared in the log. Sorry for the false alarm. 😅

**Comment by troglobit** [comment]
Ah good, you found it yourself! :)

Yep, Finit retries 10 times before giving up. You can try `task` and `run` for oneshot tasks to run once per runlevel.

**Comment by troglobit** [comment]
Maybe we can close this issue now?

**Comment by villains** [comment]
Absolutely. Sorry, I was away for the weekend.
