### ISSUE TITLE
could tty wait for a service?

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#108]
I am playing around with elogind. The good news is that it really works. But when i wrote i automatical-login tty.conf in `/etc/finit.d`, it started without session tracking because it just started really fast, faster than elogind service.

**Comment by troglobit** [comment]
Cool!

Yeah it should definitely be possible, but isn't today unfortunately. I have on my TODO list to refactor the complete TTY handling into a regular service (`svc_t`), specialized for TTY.  That would make it possible to add a condition to the `tty` directive, something like this:

    tty [12345] <svc/sbin/elogind> /dev/tty1 115200 noclear vt220

**Comment by xhebox** [comment]
Good to hear that! No hurry, i can wait :).
