### ISSUE TITLE
service dependency

### ISSUE THREAD

**Issue by 0verse** [troglobit/finit#114]
I'm wondering if it is possible to create a service or a condition that starts after when tty.conf is started? I would like to start the sway compositor on tty1 from a service if it is possible. Right now, I manage to start sway through .mkshrc file like this: 
`if [ $(tty) = "/dev/tty1" ]; then sway; fi`

**Comment by troglobit** [comment]
You can start a display manager, like lightdm, as a service. That would handle the login.  Finit has no support for user-level services, like systemd, that start when you log in to a tty.

**Comment by 0verse** [comment]
Ok thanks!
