### ISSUE TITLE
Suppressing or clearing kernel messages prior to init process?

### ISSUE THREAD

**Issue by dbuzz111** [troglobit/finit#117]
I have been hacking around for a while without much luck. I am trying to clear a ugly kernel message prior to the init process. Any way to clear it or ideally suppress
<img width="705" alt="Screen Shot 2019-04-11 at 6 43 19 PM" src="https://user-images.githubusercontent.com/41963652/56004646-b779d280-5c89-11e9-8797-9e36eb5f68b4.png">
 it?
I tried kernel.print 0 0 0 0 with no luck
Attached is a screenshot that shows a bit clearer what I am dealing with.

You see the failed to mount message

**Comment by troglobit** [comment]
Well, that's an error message from Finit which it prints to the kernel log since there's nothing else available.  I'd suggest fixing the problem; adding the /sys directory to your rootfs or enabling sysfs in your kernel.  Rather than commenting out the code path in Finit.  

Another option you have is to patch the kernel:

```patch
Index: linux-3.0.17/kernel/printk.c
===================================================================
--- linux-3.0.17.orig/kernel/printk.c
+++ linux-3.0.17/kernel/printk.c
@@ -58,7 +58,7 @@ void asmlinkage __attribute__((weak)) ea
 
 /* We show everything that is MORE important than this.. */
 #define MINIMUM_CONSOLE_LOGLEVEL 1 /* Minimum loglevel we let people use */
-#define DEFAULT_CONSOLE_LOGLEVEL 7 /* anything MORE serious than KERN_DEBUG */
+#define DEFAULT_CONSOLE_LOGLEVEL 0 /* anything MORE serious than KERN_DEBUG */
 
 DECLARE_WAIT_QUEUE_HEAD(log_wait);
```

**Comment by dbuzz111** [comment]
Thanks! You are awesome! 
I got even luckier to learn that I can pass the log level via grub and don't even need to recompile

GRUB_CMDLINE_LINUX_DEFAULT="quiet nomodeset loglevel=0"

Thanks again!

**Comment by troglobit** [comment]
No problem, good luck! 😎
