### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by winkmichael** [troglobit/finit#118]
I see you mention in the documentation "append="init=/sbin/finit splash"" but I was unable to any reference in the code or documentation further about using it. I experimented with the fbdev module and didn't get much further. 

Any hints on how to setup a splash screen, and I will beg even further about the idea of a shared splash logo that also shows the init process on the bottom as you really want to show this lovely init process, or a splash on a sleep that then shows the init process.

Thanks again for your help and time!

**Comment by troglobit** [comment]
The only thing the splash option does is to disable all logging to the screen.  This to allow a 3rd party
plugin to use the screen instead, like a splash plugin.  All this was mostly to play with for another project of mine.  You can see the splash plugin source I used here:

 https://github.com/troglobit/troglos/blob/master/packages/finit/plugins/logo.c

So yeah, what you suggest sounds cool, but there's nothing there (yet).

**Comment by troglobit** [comment]
Keyword 'splash' has now been removed, for the upcoming v4.0 release.  Was too confusing.
