### ISSUE TITLE
How to set env variables before starting a service?

### ISSUE THREAD

**Issue by deboot** [troglobit/finit#125]
Sorry! I do not see any env variables examples, so how it works?

**Comment by troglobit** [comment]
For that you'll have to use wrapper scripts. See this part of the docs ->

https://github.com/troglobit/finit/blob/master/doc/config.md#service-wrapper-scripts

**Comment by troglobit** [comment]
@deboot Did you get it working with wrapper scripts?

**Comment by deboot** [comment]
OK, thank you.

**Comment by troglobit** [comment]
OK, closing issue then.
