### ISSUE TITLE
SIGCLD is not defined by MUSL Libc

### ISSUE THREAD

**Issue by emolitor** [troglobit/finit#126]
finit fails to build with MUSL Libc. Looking at the error it appears that SIGCLD is the issue as that is not define in MUSL.

The following ifdef patch fixed the issue for me

--- a/finit-3.2-rc3/src/sig.c	2020-04-26 18:02:20.874637591 +0100
+++ b/finit-3.2-rc3/src/sig.c	2020-04-26 18:12:44.279665981 +0100
@@ -144,7 +144,9 @@
 	/* Archaic names for compatibility.  */
 	{ SIGIO,     "SIGIO"     },
 	{ SIGIOT,    "SIGIOT"    },
+#ifdef SIGCLD	
 	{ SIGCLD,    "SIGCLD"    },
+#endif
 };

 void mdadm_wait(void);

**Comment by troglobit** [comment]
Funnily enough, I fixed that this morning in 37d92e8 :-)
