### ISSUE TITLE
make fails with make[1]: *** No rule to make target 'initctl.so.so', needed by 'all'.  Stop.

### ISSUE THREAD

**Issue by jhdulaney** [troglobit/finit#13]
make[1]: *** No rule to make target 'initctl.so.so', needed by 'all'.  Stop.
Makefile:60: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhdulaney** [comment]
(With git pull as of 21/10/2015)

**Comment by troglobit** [comment]
Interesting, I had a minor regression like that earlier, but I thought I'd fixed that ... what environment are you building on/targeting?  I mostly use Debian/Ubuntu hosts and sometimes target very raw embedded systems.

**Comment by jhdulaney** [comment]
I'm on Fedora, doing this in a virtual machine.

**Comment by jhdulaney** [comment]
I got it to build by editing this line in config.mk:

OBJS       += $(addsuffix .so, $(addprefix plugins/, initctl.so hwclock.so tty.so urandom.so x11-common.so dbus.so bootmisc.so alsa-utils.so))

to:

OBJS       += $(addsuffix .so, $(addprefix plugins/, initctl hwclock tty urandom x11-common dbus.so bootmisc alsa-utils))

**Comment by troglobit** [comment]
OK.  Please tell me a little bit more about your environment and how you tried to build:
- What version of Fedora are you using?
- How did you call the `./configure` script to generate that `config.mk` file

**Comment by troglobit** [comment]
I'm guessing that you listed the arguments to `./configure --with-plugins=` *with* the .so extension, right?  I've attempted to clarify the configure and build instructions in 44579cc ... hope this helps!

**Comment by jhdulaney** [comment]
Yep, that was it, oops.  I read the documentation a bit literally

**Comment by troglobit** [comment]
OK, good then I understand better, thanks! :+1:
