### ISSUE TITLE
Building with --enable-rw-rootfs fails

### ISSUE THREAD

**Issue by jhdulaney** [troglobit/finit#15]
If you configure with --enable-rw-rootfs make fails as follows:

service.o: In function `service_start':
service.c:(.text+0x608): undefined reference to `getuser'
collect2: error: ld returned 1 exit status
common.mk:22: recipe for target 'finit' failed
make: *** [finit] Error 1

**Comment by troglobit** [comment]
Between configure runs you have to (at least) perform a `make clean`.  You can only get that
build error when either service.c or helpers.c has not been properly rebuilt.

Sorry for the inconvenience.
