### ISSUE TITLE
Q: is Finit support FreeBSD ?

### ISSUE THREAD

**Issue by AymenStudios** [troglobit/finit#162]
Can Finit be used in FreeBSD and the other UNIX and unix-like systems?

**Comment by troglobit** [comment]
Nope.  At least not currently.  It relies heavily on Linux-specific kernel features.  In theory it's definitely possible to abstract away this, like inotify etc., but it's a lot of work.  For me personally there's no interest currently in the BSDs for this project. My time is also very limited, so it's unlikely I'd be able to even review patches if someone attempted a port.

Happy to see the interest though :-)
