### ISSUE TITLE
Hardcoded /etc/hostname gives wrong hostname

### ISSUE THREAD

**Issue by AwlsomeAlex** [troglobit/finit#163]
Hello, I'm currently using finit-4.0-rc3. I hardcode the hostname of a System Image at /etc/hostname as 'natickos'. However, when I type 'hostname' on the virtual system, it returns 'naticko'. It seems the last letter is missing. It's running BusyBox (master) and musl 1.2.2 if that's helpful. If you need any more information please let me know. :)

**Comment by troglobit** [comment]
Woah, that's weird!  My initial though was that I've gone off-by-one somewhere, but I've failed to reproduce your problem.  Tried first on our buildroot derivative, NetBox, which uses glibc + busybox, then with Alpine 3.13 which has musl and busybox ... no luck.  The code looks right, maybe it's the hostname tool that somehow fails?  Try checking what ash says if you add `\h` to your PS1 and see if you get the same result.

I'm not saying this isn't a bug in Finit, I just cannot reproduce.

Btw, really glad to see someone else playing around with Finit :)

**Comment by AwlsomeAlex** [comment]
Interesting... when I run the system image fresh from the forge, this happens:
`naticko# cat /etc/hostname`
`natickosnatickos# `

But once I modify the file and logout, it works:
`natickos# cat /etc/hostname`
`natickos`
`natickos#`

All of my files appear to be missing a newline! 😅 `/etc/hostname` isn't the only file experiencing this; all of them are. Definitely something on my end, but thank you for the swift response!

And yes, I've been enjoying finit. Keep up the great work!

**Comment by troglobit** [comment]
Yeah, I tried without trailing newline as well, not even that tripped up my system.  Could be a regression in busybox:master.  

Cheers, the 4.0 release will be out in a couple of weeks at the latest! :-)
