### ISSUE TITLE
User should be able to set up hotplug from finit.conf

### ISSUE THREAD

**Issue by villains** [troglobit/finit#17]
On an embedded system I am working on, I patched finit to enable kernel hotplugging to use busybox mdev.

Right after the call to banner() in main(), I inserted the following code:

```
#ifdef EMBEDDED_SYSTEM
	fp = fopen("/proc/sys/kernel/hotplug", "w");
	print_desc("", "Enabling hotplug");
	if (fp) {
		fputs("/sbin/mdev", fp);
		fclose(fp);
		print_result(0);
	}
	else {
		print_result(1);
	}
#endif
```

This is a hacky solution suitable for my needs, but possibly other embedded users may find something similar useful in their work.

Finally, as always, thanks for your work on finit!

**Comment by troglobit** [comment]
So happy to see other people starting to use Finit! :smiley: 

I've been considering something like this for a couple of years now, but at work¹ we simply configure the kernel to use a different helper, this is both easier and saves an (albeit microscopic) bit of time at boot:

    CONFIG_UEVENT_HELPER_PATH="/sbin/mdev"

So the need for controlling this from userspace hasn't been that strong. I like the idea you are presenting, but the code is a little too specific (for lack of better wording). Maybe this could instead be included in a whole slew of kernel tweaks one might want to set early?  Similar to what we do later with `sysctl.conf`.

¹) Westermo

**Comment by villains** [comment]
Thank you, CONFIG_UEVENT_HELPER_PATH is exactly the solution.
Can't believe I didn't look at that. I learned something new today. :satisfied:

**Comment by troglobit** [comment]
@villains Happy to help! :smirk:
