### ISSUE TITLE
Docs, Typos in doc/bootstrap.md

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#187]
In bootstrap.md doc, it is stated:
`In (19) and (22) tasks and services defined in /etc/finit.conf and /etc/sysctl.d/*.conf are started. Remember, all service and task stanzas are started in parallel and run in sequence, and in the order listed. Hence, to emulate a SysV /etc/init.d/rcS one could write a long finit.conf with only run statements.`

I think (19) and (22) should be (19) and (23).

Also, it states `/etc/sysctl.d/*.conf` but I think it should be `/etc/finit.d/*.conf`)

**Comment by troglobit** [comment]
Thanks, I'll fix this in the upcoming 4.2 release! :)
