### ISSUE TITLE
Feature request, Extra variables passed to scripts

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#189]
Currently, **SERVICE_IDENT** is passed to pre and post scripts, this is very helpful.

I would like to propose a few additional variables:
- SERVICE_ENV_FILE (name and path of env file if passed)
- SERVICE_ENV_FILE_EXISTS (1 if file exists and was loaded, otherwise 0)
- SERVICE_TYPE (one of "task","run","service","pre" or "post")
- SERVICE_CONF_DIR (variable set --with-sysroot during compilation, I think by default this should be "/etc/default:/etc/conf.d")

**Comment by troglobit** [comment]
Thanks, I'll consider it.

**Comment by troglobit** [comment]
Implemented, with slight change to proposal.  SERVICE_TYPE is task/run/service, while SERVICE_SCRIPT_TYPE is pre/post.  The SERVICE_CONF_DIR is set to "/etc/default:/etc/conf.d", or "/etc/default:/etc/conf.d:PATH" when `--with-sysconfig=PATH` is given at configure time.
