### ISSUE TITLE
Feature request, allow running as PID >1 for testing

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#192]
Is there a way to test Finit when run from another init system? I couldn't see this and it didn't seem to work when trying it but maybe I missed it.

Right now, recompiling my system (I'm using a readonly squashfs filesystem with a tmpfs and flash mount), it's a bit time consuming to recompile, load flash, boot and test.

It would be great if I could run finit where it wasn't run as PID 1 for testing use cases. I found s6-supervise has this option you can simply run it from anywhere and it will spawn all the apps under it's own process tree. This means you can keep the current init system in place during testing and just run finit (or s6-supervise) as one of the services under it.

When your ready to switch over to finit being the main process manager, you know everything is all tested.

**Comment by hongkongkiwi** [comment]
I've realised that the way finit handles all the low level stuff, this is probably a little bit too much work. This is more useful to me where I have a readonly system as the main system so testing changes quickly requires rebuilding the image.

I got around it by just changing the init system and rebooting again.

**Comment by troglobit** [comment]
You've already closed this, but the whole purpose of an init is to be the first process.  Finit is not designed to just run as a process monitor or something.  It does however support running in a container environment, e.g. LXC.
