### ISSUE TITLE
Feature request, finit status NAME should show all services if multiple ids

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#197]
If I have three services e.g. 
* mysesrvice:a
* myservice:b
* myservice:c

Then I do `initctl status myservice` it displays mysesrvice:a because it apperas first in the config. My suggestion is that it should show all status's for all subservices. Then if I want to drill down I could use `initctl status myservice:b`. 

As an addon to this, can I also suggest a command that given a service name e.g. myservice, it returns all ids associated with it.... e.g.
`initctl ids myservice` and it would return:
```
myservice:a
myservice:b
myservice:c
```

**Comment by hongkongkiwi** [comment]
Or maybe.... a better way might be to show nothing if passing a name when there are more than 1 id specified.

**Comment by troglobit** [comment]
This was actually part of the 3.x series, it must've gotten lost in the big refactor.  We'll look into restoring the functionality in a later release cycle.
