### ISSUE TITLE
Add status/result of `ifup -a` to log or `initctl daemon-status`

### ISSUE THREAD

**Issue by troglobit** [troglobit/finit#228]
While debugging an issue at $DAYJOB we realized there was no way to know *why* network bringup resulted in `[FAIL]` output.  There was no log output, and there was no other way to show the status.

So, at the very least, we need some sort of syslog output.  The `popen()` output of the command maybe.  

A more ambitious take could be to add a new command, here the ugly (too long), `initctl daemon-status` is used.  It could be used to show a lot of other neat output as well, e.g. Finit version, a list of loaded plugins, result of all bootstrap tasks (which are pruned from Finit after bootstrap), etc.

**Comment by hongkongkiwi** [comment]
This would be very helpful for me also, I find often some things fail and I don't know why, for example dbus fails to generate uuid or filesystems fail to mount but it would be good to simply look at a log and see what caused it (without having to launch initctl in debug mode and sift through the logs).

**Comment by troglobit** [comment]
@hongkongkiwi The working idea right now, is to wrap all these calls in `popen()` and generate log messages. This seems to be the best approach since there are a lot of tools (I'm looking at you udhcpc) that spew a lot to stdout/stderr instead of syslog on `ifup -a`.

I have a working prototype, but I'm also looking at the output from other commands, such as `mount -na`. So this may take a few days, and I may need to limit the scope of this work. But it'll be part of the 4.3 release in some form.

**Comment by troglobit** [comment]
Fixed in ef9e9ec and 6fa3aa4.
