### ISSUE TITLE
Add finit.config=/etc/custom.conf cmdline (kernel) for different finit.conf file

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#235]
I would like (for testing) to specify a different /etc/finit.conf file. Is it possible to pass a kernel param to specify what config file init uses?

**Comment by troglobit** [comment]
Similar to #224, neat request if `finit.config=/path/to/file` existed then overrides for tests and similar would be possible.

**Comment by hongkongkiwi** [comment]
This would be useful to me, if implemented, perhaps we could hardcode allowed filenames at compile time? That way user cannot arbitrarily specify a filename and then when something is passed finit just checks against kv to see if it was allowed at compile time.

Might help to mitigate any possible security issues? Just a thought today about this.

**Comment by troglobit** [comment]
Good idea, I was a bit concerned about the security aspects as well! Thanks :)

**Comment by hongkongkiwi** [comment]
What about this?
- rcsd dir is configurable in finit.conf (value in finit.conf overrides any hardcoded setting)
- fstab.config=/etc/finit.conf is configurable to point to a different .conf file

This works since finit.conf is read first (right?)

**Comment by troglobit** [comment]
Yes, that would work. (I'm assuming you meant `finit.config=/etc/finit.conf`, not fstab :)

**Comment by hongkongkiwi** [comment]
Yep! :)

**Comment by hongkongkiwi** [comment]
I'm receiving these log messages (I don't have any file named /etc/fstab). The fstab file should be compiled as /etc/fstab.noslot I believe 
(SIDE NOTE: is there anyway to check what the compiled in vars are? possible to display this info somewhere e.g. initctl ver)

```
[ ⋯  ] Checking filesystem sysfsWARNING: couldn't open /etc/fstab: No such file or directory
[ OK ]
[ ⋯  ] Checking filesystem sysfsWARNING: couldn't open /etc/fstab: No such file or directory
[ OK ]
[ ⋯  ] Checking filesystem sysfsWARNING: couldn't open /etc/fstab: No such file or directory
[ OK ]
[ ⋯  ] Checking filesystem sysfsWARNING: couldn't open /etc/fstab: No such file or directory
[ OK ]
[ ⋯  ] Checking filesystem sysfsWARNING: couldn't open /etc/fstab: No such file or directory
[ OK ]
[ OK ] Mounting filesystems from /etc/fstab.slot.flash_recovery_rootfs.0
[ OK ] Enabling system swap
swapon: failed to parse /etc/fstab: No such file or directory
```

**Comment by troglobit** [comment]
Great, thanks for testing this!  I'll have a look at what this could be later tonight.  When I tested I had the std /etc/fstab, of course ...

**Comment by troglobit** [comment]
Found two things so far, looking at BusyBox sources:

  1. swapon/swapoff do not take any alt. /etc/fstab argument (not even the util-linux counterparts on std Linux)
  2. turns out the fsck program needs /etc/fstab, or a custom `FSTAB_FILE=/etc/fstab.alt` environemnt set, this also seems to be supported by the util-linux counterpart

For swap, this was an oversight on my part and I'll see what I can do about fishing out swap partitions and files manually and calling `swapon /dev/partition` or `swapon /swapfile` from what I can find.

For fsck, I'll set the environment variable and hope it works since I don't have a system with swap to test on atm.  But I'll make note of it and test during the coming weekend. (Which is when I hope to release Finit 4.3)

**Comment by troglobit** [comment]
Ouch, I see now we both mixed up the issues a bit.  Our last three comments above should probably've been on #224 ... oh well.  I've pushed a few fixes and additions.  Again, the swap fixes have not been tested on a system with swap/swapfile yet.

**Comment by hongkongkiwi** [comment]
I wanted to clarify this feature request a bit and narrow it down.
1. Change rcsd dir to be read from finit.conf something like `rcsd_dir=/etc/mydir` (otherwise fallback to whatever is configured at compile time, or just fail if nothing configured, similar to how fstab works)
2. Finit conf can be specified from kernel comdline
finit.conf=/etc/finit.conf 

I think these two changes are very powerful and allow the user to specify completely different sets of scenarios. For example, you might want a factory test mode which you can simply specify that with finit.conf=/etc/factory_test.conf 

A similar functionality can be used with runlevels, but your limited to a few scenarios with no way to specifically name each one. Also, there are some hardcoded functionality which cannot be changed with runlevels (e.g. in my above example the rcsd_dir), so being able to specify a different finit.conf (which in turn specifies it's own rcsd_dir) would be extremely powerful.

**Comment by troglobit** [comment]
100% agree from me. Thank you for taking the time to pin this down <3
