### ISSUE TITLE
Multiple tasks with different name, but same identifier not working

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#244]
I think there might be a bug with multiple tasks with the same identifier but different names.

e.g. I have:
```
task [12345789] name:wifi :checkenabled echo "Wifi bootup is $(wifi-get-iface-enabled)" -- Wifi Enabled Check Task
task [12345789] name:lte :checkenabled echo "LTE bootup is $(lte-get-iface-enabled)" -- LTE Enabled Check Task
```

Strangely the wifi one doesn't show up in `initctl status wifi:checkenabled`, however the lte one does with lte:checkenabled

Just for some background, I'm using the name as a sort of category, so all lte related tasks are named lte, that way I can simply do initctl stop lte to stop all these related tasks. Same with wifi.

**Comment by hongkongkiwi** [comment]
I think I found the issue: 
`failed wordexp("LTE bootup is $(lte-iface-get-enabled)")`

Looks like it doesn't like shell substitution here ;)

**Comment by hongkongkiwi** [comment]
I'm closing this because it's my fault and it's not an active issue.

**Comment by troglobit** [comment]
Heh, yeah that won't work :)
