### ISSUE TITLE
Pass `env:foo` also to pre/post scripts

### ISSUE THREAD

**Issue by troglobit** [troglobit/finit#248]
### Discussed in https://github.com/troglobit/finit/discussions/240

<div type='discussions-op-text'>

<sup>Originally posted by **hongkongkiwi** April 20, 2022</sup>
I couldn't find my answer in the docs.

Are env:.... variables passed to the pre/post scripts also? I'm interested in having one place for the vars and using them both in pre: and also running the app.</div>

**Comment by troglobit** [comment]
Turns out this was partially implemented in #189, back in February, also for v4.3 ... so I'll just rip out the SERVICE_ENV_FILE* stuff and replace it with the variables sourced instead.  Basically:

    sh -ac '. /path/to/env; exec ./pre-post.sh'

This means the `env` file can be a simple `foo=bar` file, which Finit can read and call `setenv()` on all variables, and the user do not need to call `export` on all variables -- additionally, any functions defined in an env file could be used by the pre-post scripts, but would go ignored by Finit.

**Comment by hongkongkiwi** [comment]
Nice! That should make things very flexible.--
Sent from Gmail Mobile
