### ISSUE TITLE
fsck output string truncation too short

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#260]
I noticed that my startup logs look like this:
```
[ OK ] Checking filesystem /dev/mmcblk0p
[ OK ] Checking filesystem /dev/mmcblk0p
[ OK ] Checking filesystem /dev/mmcblk0p
[ OK ] Checking filesystem /dev/mmcblk0p
[ OK ] Checking filesystem /dev/mmcblk0p
```

After investigation I found that there is a hardcoded size for an output string here:
https://github.com/troglobit/finit/blob/181d9556a1364ad2977b9cbd75a4b59a4ba79d89/src/finit.c#L259

So this assumes that the string is not more than 13 chars, however I think this is not necessarily true. e.g.
- /dev/mmcblk0p1 is 15 chars
- /dev/mmcblk0p14 is 16 chars
- Some people are using: /dev/mmcblk0boot0 which is 18 chars....

So my suggestion is to set this to by default 18 chars as that should cover a majority of cases.

Additionally, if it's larger than 18 chars, for example if you had a weird case of "/dev/mmcblk0boot10" perhaps you could append `...` e.g.  `[ OK ] Checking filesystem /dev/mmcblk0boot1...` so people know it's been truncated.

Or perhaps no need to set any limit on the size?

**Comment by troglobit** [comment]
Yes, thanks for pointing this out!
