### ISSUE TITLE
finit doesn't properly reload config definitions when using initctl reload <service>

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#263]
I'm doing some development and testing on the device using finit.

I've found that when I change the bin that a service is pointing to, e.g. 
/tmp/mybin and change to something like /usr/bin/mybin issuing a `initctl reload` doesn't correctly change the service definition or atleast it appears to still refer to the old command in: initctl status

This isn't a problem as I just reboot after major service changes (conditions or command), but I think it's worth adding some additional tests for these cases there's definately a few minor bugs here.

**Comment by troglobit** [comment]
OK. Do you set name: and :id on these services?  If not, the only handle Finit has to track the uniqueness is the command name. 

Would be great if you could include the before and after shots of the config stanza.

**Comment by hongkongkiwi** [comment]
Yes I'm using name and id but it seems to not matter if I do or don't.

Perhaps this is not true, but logically I expect that `initctl reload` reloads all services and `initctl reload <service>` reloads that specific service.

```
task [12345789] name:sys :test env:/tmp/conftest /tmp/test -- test123
```

If I do a `initctl reload` it appears to pick up the config change to bin as well as reloading all other services, however if I do an "initctl reload sys:test" then it doesn't.

e.g. my config is now:
```
task [12345789] name:sys :test env:/tmp/conftest /tmp/test "$TEST" -- test123
```

But in status is still appears as the old config no matter how many times I do: `initctl reload sys:test` only `initctl reload` works.

I did find before that even a general reload didn't update (I just ended up rebooting), but I can't replicate that situation, so lets pretend it didn't exist until I can find a way to reproduce it, it may even be I was running to the above without realising it.

**Comment by troglobit** [comment]
Maybe this command should be dropped from the documentation and online help?  As I mentioned, unfortunately we have to keep it to not break other tooling built around `initctl`, but if we remove it from the docs it's at least not confusing other users.

I'll check with the other tooling, maybe we can check for `-b` as well, and if that is *not* set and reload has an argument we can give an "invalid command argument" error message or something.

**Comment by hongkongkiwi** [comment]
hmmm, I use initctl reload <service> to send a reload signal to some services. It's helpful because then I don't need to worry about whether it supports HUP or not (finit will take care of hup or restart).

Perhaps it might be better to have a named command such as `initctl hup <service_name>` and keep initctl reload <service_name> undocumented? the hup command could specify that it sends a hup signal or restarts depending on what kind of service it is.

(What happens if you send a reload to a task?)

Alternatively, we could make initctl reload to be something like initctl reconfigure? hah but reload is so nice to type and simple.

**Comment by troglobit** [comment]
Yeah I think that was the original use-case also for us (don't have to know what's supported).  

I agree, we could expose the same functionality with another name.  Dunno about `hup`, worry that folks may confuse it with `signal HUP` ... 

(Dunno, and now you've got me worried, I'll try to investigate on the train to work :)

Nah, no more renaming stuff. We have what we have, let's try to tie up loose ends. I'd very much like to get the release out.

**Comment by troglobit** [comment]
Reloading a task allows it to run again in the same runlevel.  So that was a bit of a surprise, but this is where we hare now, apparently :rofl: 

OK, I'll just update the docs and add a big disclaimer about the corresponding Finit .conf *not* being reloaded.

**Comment by troglobit** [comment]
There, both the README and [initctl(8)](https://man.troglobit.com/man8/initctl.8.html) manual page updated.
