### ISSUE TITLE
initctl signal and other commands should support -q

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#266]
I have some services which may or may not be available when I want to send a signal. (they are being sent signals very early via mdev) The debug output is quite noisy.

I propose that initctl signal, reload, restart, stop/start should support a **-q** flag which simply returns an error code if the service doesn't exist rather than any error message. This is very useful for scripts where we don't need the error message just the return code.

Here's what happens without -q
```
# initctl -q signal test 9
No such task or service(s): test

Usage: initctl signal <NAME>[:ID] <S>
```

**Comment by troglobit** [comment]
Excellent point, thanks!

**Comment by troglobit** [comment]
There fixed.  As an added bonus I've audited and aligned the exit codes with LSB and BSD sysexits.h, same as detailed in [systemd.exec(5)](https://www.man7.org/linux/man-pages/man5/systemd.exec.5.html#PROCESS_EXIT_CODES).

**Comment by hongkongkiwi** [comment]
Thanks! Very helpful.
