### ISSUE TITLE
Add option in initctl cond dump to get only specific type of conditions.

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#272]
It would be great to have an option to only show only a specific type of conditions when using initctl cond dump. 

Perhaps we could support filtering by the first path of the path e.g.
`initctl cond dump usr`
`initctl cond dump service`
`initctl cond dump task`
`initctl cond dump net`
`initctl cond dump pid`

This would make it very easy to view conditions of a specific type quickly.

**Comment by troglobit** [comment]
Basic prefix matching added in [6286ede](https://github.com/troglobit/finit/commit/6286ede98584f0708b0b11cca2eeafd8de9b18e0)
