### ISSUE TITLE
restart:always feature or changing restart: count to an int

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#279]
For the next finit release, I would like to request `restart:always` be implemented or something similar. Or alternatively could we increase the `restart:` to an int (2147483647) that would also solve it.

There is a "respawn" option as mentioned in #242 , but this bypasses the restart mechanism so there's no way to set a time between restarts which for my case is pretty important.

Having a task instantly restart on crash is not desirable for low cpu systems.

**Comment by troglobit** [comment]
Yes, agreed.
