### ISSUE TITLE
Search for plugins in /usr and /usr/local too

### ISSUE THREAD

**Issue by troglobit** [troglobit/finit#284]
Now that https://github.com/troglobit/finit-plugins exist we need to be able to look for plugins in other directories as well as the default.

**Comment by troglobit** [comment]
Yes exactly, the default is whatever you call configure with, the `--libdir` option sets the install directory, which in turn is based on `--prefix`, iirc ... so adding a default search patch based on /usr/lib/finit/plugins and /usr/local/lib/finit/plugins feels like a good idea.  Plugins are loaded waaaaaay before any .conf file can be read, so it has to be a configure/compiple-time thing.  So maybe expose it in the configure script?

**Comment by hongkongkiwi** [comment]
Compile time setting makes sense :)
