### ISSUE TITLE
initctl restart doesn't work on crashed service

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#285]
This is a minor usability point and perhaps you disagree here but I'll throw it out there.

I had a crashed service and I tried to use: `initctl restart <service>` but it did not work.

It did nothing until I used `initctl start <service>` but ideally I shouldn't need to check the state of the service to know which command to use.

It would be great if running initctl restart works no matter whether the service is, crashed, stopped or running.

**Comment by troglobit** [comment]
No I agree completely, that should definitely work. Thank you for taking the time to report it!
