### ISSUE TITLE
Problem with downloaded dockerfile 

### ISSUE THREAD

**Issue by pwFoo** [troglobit/finit#290]
Hi,

I downloaded finit / Dockerfile from article:
https://troglobit.com/post/2022-01-16-finit-v4.2-released/

There were build problems I need to fix

1. #288 (and found typo in documentation #289)
2. Changes in Dockerfile
 Add build options. 
 ```
 RUN     sed -i 's/--with-keventd/--with-keventd --enable-static --enable-resolvconf-plugin --with-sulogin --enable-kernel-cmdline/' ./contrib/alpine/build.sh
 ``` 
 Better set by env / args during build ?

Copy by so* instead of an hardcoded version string
```
RUN     cp -a \
        /lib/ld-musl-x86_64.so.1 \
        /usr/local/lib/libite.so* \
        /usr/local/lib/libuev.so* \
        \
        lib/
```

 And third part:
 ```
#RUN    ln -s libite.so.5.3.0 libite.so.5
#RUN    ln -s libuev.so.2.2.0 libuev.so.2
 ```

**Comment by troglobit** [comment]
On second thought, where did you find that Dockerfile for Finit?  I've looked around both on my blog and in the Finit repo -- but I cannot find a Dockerfile?  

Maybe your issue was a question about how to write a Dockerfile for Finit?

**Comment by troglobit** [comment]
No replies to my questions regarding the Dockerfile, and issue #288 has just been closed.  So I'm closing this issue too.
