### ISSUE TITLE
/sbin/shutdown force after timeout option?

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#295]
Is it possible to pass a timeout via the /sbin/shutdown command so that finit will force a shutdown if shutdown has not been completed in a certain time?

`/sbin/shutdown --reboot --force-after-timeout-ms 5000`

So this would attempt a normal shutdown and if the whole process hasn't completed after 5000ms then it will just immediately take action.

This means no matter what we are guaranteed to reboot after a timeframe.

**Comment by troglobit** [comment]
Interesting, yes it's possible!  I'll have a look at it :)

**Comment by troglobit** [comment]
Just merged my patch queue today, a new timeout option is available to reboot/shutdown/poweroff.  If you have the time, please tell me what you think :)
