### ISSUE TITLE
Add plugin hook after unmount

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#302]
Hi, I am looking into creating a plugin that's run after the system is unmounted. I'm going to make it using the normal plugin architecture because it's nice and clean and I can use the official finit branch.

Is it possible to add an extra hook so I can run some code to send something to serial port after unmount has been completed? e.g. HOOK_UNMOUNT_COMPLETE or something?

Maybe it's there and I missed it but according to the docs there's only [HOOK_SHUTDOWN](https://github.com/troglobit/finit/blob/master/doc/plugins.md)

Presumably it probably would hook in [at this point?](https://github.com/troglobit/finit/blob/dc547317c9c3bab58c1206791191327367193735/src/sig.c#L373)

I could see this being useful to create a cleanup hook for some embedded devices which need to set a particular state when cleanly powering down. In my case I will send out a serial message to let the co-processor know that we are OK to hard power off but I could imagine other people would find uses as a "Last will and testament feature".

**Comment by hongkongkiwi** [comment]
Well, I guess if I'm asking for something new, maybe it makes sense to have two new hooks:
**HOOK_ALL_SERVICES_STOPPED** - this could hook in after all services are stopped but before the disks are unmounted, this is incase plugins want to access something on disk 
**HOOK_UNMOUNT_COMPLETE** - useful for safe power off at this point or something that requires the system to be unmounted cleanly

**Comment by troglobit** [comment]
Hmm, it's a little bit tricky. The point you reference is after we've unloaded the plugins in `plugins_exit()`, and we need to unload as much as possible to be able to unmount ... but I guess for the latter hook you could use a "hook script", right?

**Comment by troglobit** [comment]
Yeah, I meant add the hook point to the code, after all the umounts, but then it would only be possible to run scripts there.  So a limitation for that specific (very late) hook point.

**Comment by hongkongkiwi** [comment]
That would be great. 

But ahh one thing.... I do need access to a serial device ? (/dev/ttyS1) does /dev get unmounted?

**Comment by troglobit** [comment]
Hmm, /dev is usually a devtmpfs these days ... currently Finit unmounts that too, but I think that (devtmpfs) would be OK to add an exception for.  That needs a separate issue, I'll create one right away!

- [ ] Add exception for devtmpfs in `unmount_regular()`

**Comment by troglobit** [comment]
The final hook names changed slightly, see [doc/plugins.md](https://github.com/troglobit/finit/blob/master/doc/plugins.md#hooks) for details and an example.
