### ISSUE TITLE
[BUG] Latest finit commit causes initctl to time out

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#307]
I just compiled the latest finit and I'm having these issues:
```
~ # initctl status
initctl: Timed out waiting for reply from Finit.
```

This version works fine: `10437887fcd5eecef8f10bd59320b51d5093dbfa` 
Next commit breaks things: `37e3be9a0dfef0ca82805c92b8ea2549bd022149`

`/sbin/finit 6` also doesn't work, it just sits there (but doesn't time out)

I rebuilt a few different versions and it is consistently the same issue, something breaks between these two commits.

**Comment by troglobit** [comment]
Thank you so much for reporting back!  The automated tests seem to run fine though, and they do a lot of `initctl status`.  Maybe you could share your configure command, and config.log?

**Comment by troglobit** [comment]
Great, thanks!  You can attach files to issues these days on GitHub, very handy :)

I'll try to have a look at this over the next coming days.

**Comment by troglobit** [comment]
Hmm, I see you both `--enable-static` and `--enable-shared`?  At least the `--enable-static` is is not often tested (and never by me) and has been very difficult to support.  For instance, the external finit-plugins repo only supports dynamically loadable .so files, but there are other things as well like features of GLIBC that aren't available when building static applications.

**Comment by hongkongkiwi** [comment]
Thank you, the latest refactor fixes all my issues 🥇 💯 

For `--enable-static` or `--enable-shared` I actually don't specifically set either of those, so it's curious. Lets try to dig in a little bit more.

**Comment by troglobit** [comment]
Sorry to hear.  It's going to be very hard to get to the bottom of this if I cannot reproduce.

**Comment by troglobit** [comment]
Hi @hongkongkiwi, recently I debugged and fixed #310, which might have some bearing on your problem.  I'd be very interested to hear if you still experience problems using the latest master.

**Comment by hongkongkiwi** [comment]
Thank you, hooray it's fixed and seems to work ok now.

Havn't had time to fully test it today, but it appears to be fixed as the bootup is fine with no more timeouts :)

**Comment by troglobit** [comment]
Ah, that's great news, thank you for the feedback! :heart::tada:
