### ISSUE TITLE
Set fixed conditions in device tree?

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#311]
I would like to set some conditions in finit based on whats in the device tree.

This way certain services can be started based on hardware configuration.

Do you think a finit plugin is the best task for this or do you think it makes sense to have this as a built in feature? If it's in a finit plugin, could you give me a code snipped to set a condition at an early stage? (I would like to set these just after fs are mounted)

e.g. have a finit section in the dtb:
```
finit {
   conditions={
      conditiona;
      conditionb;
      conditionc;
   };
};
```

**Comment by troglobit** [comment]
It could definitely be a plugin, but I don't think you'll need it.

At $OLDJOB We did this, which was pretty neat.  The first two links is the common call to set up a static/one-shot condition based on the product model and the third is an example of how to use it:

 - https://github.com/westermo/netbox/blob/master/board/common/rootfs/etc/finit.d/system-init.conf
 - https://github.com/westermo/netbox/blob/master/board/common/rootfs/lib/system/ident
 - https://github.com/westermo/netbox/blob/master/board/envoy/rootfs/etc/finit.d/system-envoy.conf

> Remember, static/one-shot conditions are always asserted, following the current configuration generation.

**Comment by troglobit** [comment]
I've added this to the v4.4 release with the intent of documenting the above trick.
