### ISSUE TITLE
[bug] Double name printed when hook script fails

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#316]
At compile time, I have set my hook scripts directory to: `/usr/share/finit/hooks`

One of my hook scripts failed and the bootup showed this line:
```
[ ⋯  ] Calling /usr/share/finit/hooks/sys/up/notify-mqtt.sh/usr/share/finit/hooks/sys/up/notify-mqtt.sh: source: line 2: can't open '/usr/share/mqtt-api.env': No such file or directory
[FAIL]
```

The source error is expected as I mistyped something, however it looks like there is a double up on the script name here in the output.

**Comment by troglobit** [comment]
Thanks for reporting, will have a look!

**Comment by troglobit** [comment]
Indeed, was caused by #317.
