### ISSUE TITLE
Bug with net device exist detection

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#322]
It appears to be a bug here, not sure how it's possible that the device doesn't exist (e.g. it's waiting for it to exist) when it's up.

Maybe we can just make an assumption that the device MUST exist if up is detected? So whenever up or down or any other event happens then it will automatically flag exist as true.

Also side note: is there a size limit for names ? My name was lte:network-autoconnect-dialer but got shortened to network-autocon , I might have missed it in the docs.

`initctl status lte:network-autocon`

```
     Status : waiting (code=exited, status=0/SUCCESS)
   Identity : lte:network-autocon
Description : LTE Network Autoconnect Dialer
     Origin : /etc/finit.d/network-lte.conf
Condition(s): <-<!net/wwan0/exist,+net/wwan0/up,+usr/dev:lte-cdc_exist,+usr/lte:iface_enabled,+service/co6:lte/ready>
    Command : /storage/lte-network-autoconnect-dialer
   PID file : none
        PID : 0
       User : root
      Group : root
     Uptime : N/A
   Restarts : 0 (0/10)
  Runlevels : [--2345-7--]
```

**Comment by hongkongkiwi** [comment]
Apologies, I had << instead of < for my conditions, after fixing that it now works.

**Comment by troglobit** [comment]
No worries! :)
