### ISSUE TITLE
Bootmisc plugin does not set up /var/lock/subsys before dbus plugin runs

### ISSUE THREAD

**Issue by joerg-krause** [troglobit/finit#33]
I am using [Buildroot](https://buildroot.org) to build an embedded Linux system. The rootfs filesystem does not create the directory `subsys` in `/var/lock`. Actually, it is only created if a user-space process like dbus is started. As finit is the first process, the directory `/var/lock/subsys` does not yet exist and finit throws an error:

```
finit: Failed creating directory /var/lock/subsys/messagebus: No such file or directory
```

EDIT: Note that `/var/lock` is a symlink to `/tmp`.

**Comment by troglobit** [comment]
Thanks for the report!  Will change the `makedir()` calls to use the libite (-lite) API `mkpath()` instead. Hope that's sufficient until someone who uses dbus comes up with a better patch.

**Comment by troglobit** [comment]
The 05938a8 fix turned out to be a better patch.  Thanks again! :smiley:

**Comment by joerg-krause** [comment]
Many thanks!
