### ISSUE TITLE
--disable-mdevd-plugin seems not respected

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#331]
After disabling the mvded plugin with --disable-mdevd finit keeps trying to look for it with: 
kernel: finit[1]:load_one():Failed loading plugin /usr/lib/finit/plugins/mdevd.so: File not found: No such file or directory

In my buildroot package, I specifically delete the file if it's been disabled so hence why it's missing here, but it seems to not be respecting the --disable-mdevd-plugin

This might not matter since we are deleting it but I thought I would post it just in case it affects other modules.

Here's my configure line:
```
./configure --target=arm-co6-linux-uclibcgnueabihf --host=arm-co6-linux-uclibcgnueabihf --build=x86_64-pc-linux-gnu --prefix=/usr --exec-prefix=/usr --sysconfdir=/etc --localstatedir=/var --program-prefix= --disable-gtk-doc --disable-gtk-doc-html --disable-doc --disable-docs --disable-documentation --with-xmlto=no --with-fop=no --disable-dependency-tracking --enable-ipv6 --disable-nls --disable-static --enable-shared -q --prefix=/usr --with-plugin-path=/lib/finit/plugins:/usr/lib/finit/plugins:/usr/local/lib/finit/plugins --exec-prefix= --disable-contrib --disable-doc --disable-silent-rules --with-fstab=/etc/fstab.noslot --with-heading=ReadySight --disable-auto-reload --with-config=/etc/finit.conf --with-rcsd=/etc/finit.d --with-rc-local=/etc/rc.local --with-hostname=readysight --with-runlevel=3 --with-watchdog=/dev/watchdog --with-group=root --without-keventd --with-sysconfig=/etc/conf.d --enable-logrotate --enable-redirect --enable-fsckfix --disable-fastboot --disable-kernel-cmdline --disable-mdevd-plugin --enable-hook-scripts-plugin --with-hook-scripts-path=/usr/share/finit/hooks --disable-alsa-utils-plugin --enable-dbus-plugin --disable-hotplug-plugin --enable-modules-load-plugin --enable-rtc-plugin --enable-netlink-plugin --disable-x11-common-plugin --disable-modprobe-plugin --enable-tty-plugin --enable-urandom-plugin --with-random-seed=/var/lib/misc/random-seed --enable-resolvconf-plugin 'CPPFLAGS=-DDBUS_DAEMONUSER=\"dbus\" -DDBUS_DAEMONGROUP=\"dbus\" -DDBUS_DAEMONPIDFILE=\"/var/run/dbus/pid\" -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64'
```

**Comment by troglobit** [comment]
It's likely because its a (soft) dependency for another plugin.  Did you disable and remove the hotplug plugin as well?

**Comment by hongkongkiwi** [comment]
Yup, both plugins are removed.
`--disable-hotplug-plugin--disable-mdevd-plugin`

**Comment by troglobit** [comment]
It's also a softdep in the chrony and qmi-proxy plugins.  So I'd say at this point this is a valid warning.

However, since I've proposed dropping the mdevd plugin in favor of the .conf lines (#328), then we should also remove the softdeps from these plugins.  Which would make the warning go away.

**Comment by troglobit** [comment]
mdevd softdep dropped in [f6bfbc8](https://github.com/troglobit/finit/commit/f6bfbc86e972b9bccc44354a5b7077356a47d7ec) and https://github.com/troglobit/finit-plugins/commit/3000552c3d9b5bae0c7e7f4fabb77b8a32930a0f

Please see [finit-plugins/README.md](https://github.com/troglobit/finit-plugins/blob/master/README.md#notice) for more information.
