### ISSUE TITLE
Build fails when configured with --disable-inetd

### ISSUE THREAD

**Issue by villains** [troglobit/finit#35]
I'm working on a small embedded system where the finit inetd server is not required.

Compilation fails with the following errors:

> service.c: In function ‘service_register’:
service.c:579:4: error: label ‘recreate’ used but not defined
    goto recreate;
    ^
Makefile:797: recipe for target 'finit-service.o' failed
make[2]: *** [finit-service.o] Error 1
make[2]: Leaving directory '/var/shared/finit'
Makefile:1022: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/shared/finit'
Makefile:442: recipe for target 'all' failed
make: *** [all] Error 2
markus@partypants:/var/shared/finit$ git rev-parse HEAD
e3783e8bac4dce31880538332ce3f759b9a5a719
markus@partypants:/var/shared/finit$

The seems to be that in service.c line 563 where the goto label 'recreate' appears inside an #ifndef INETD_DISABLED/#endif block.

Moving the recreate labe' outside the #ifndef/#endif block results in a few more errors:

> markus@partypants:/var/shared/finit$ make
make  all-recursive
make[1]: Entering directory '/var/shared/finit'
Making all in plugins
make[2]: Entering directory '/var/shared/finit/plugins'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/var/shared/finit/plugins'
make[2]: Entering directory '/var/shared/finit'
  CC       finit-service.o
  CC       finit-sig.o
  CC       finit-svc.o
  CC       finit-sm.o
  CC       finit-tty.o
  CCLD     finit
finit-service.o: In function `service_register':
/var/shared/finit/service.c:577: undefined reference to `inetd_del'
collect2: error: ld returned 1 exit status
Makefile:546: recipe for target 'finit' failed
make[2]: *** [finit] Error 1
make[2]: Leaving directory '/var/shared/finit'
Makefile:1022: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/shared/finit'
Makefile:442: recipe for target 'all' failed
make: *** [all] Error 2
markus@partypants:/var/shared/finit$

It would appear that the inetd dependence is not completely eliminated by configuring with --disable-inetd.

Once again, thanks for creating finit. I love and appreciate the new features you are adding all the time. In particular, the "log" keyword to add to services and tasks to route stderr and stdout messages to the system logger, instead of to the serial console.

All the best!

**Comment by villains** [comment]
To follow up briefly, the attached patch applied on top of revision e3783e8bac4dce31880538332ce3f759b9a5a719 allows finit to build when configured with --disable-inetd.

Your review is needed... I am not 100% sure if I added the new #ifndef/#endif block to allow finit to function correctly with inetd disabled, and I have not tested it in any meaningful way.

Thank you & best regards!

[fix-inetd-disabled.txt](https://github.com/troglobit/finit/files/445852/fix-inetd-disabled.txt)

**Comment by troglobit** [comment]
Great stuff, and awesome timing, I was just about to start the last phase of testing before v3.0! :smiley: 
I'll have a more detailed look at it later today!

**Comment by villains** [comment]
Fantastic, thank you!
Now updating my local copies of the finit repo.
Looking forward to seeing what's new in 3.0.
All the best!

**Comment by troglobit** [comment]
No problem, just happy to see more people using it! Feedback and patches is much appreciated ☺
