### ISSUE TITLE
fsck_mode and fsck_repair not documented, and suboptimal interaction with --enable-fsckfix

### ISSUE THREAD

**Issue by az143** [troglobit/finit#366]
joachim, the fsck kernel parameter set you added in 1e1b3564dda3 is a great addition  - but a) it's not documented in cmdline.md yet,
and b) i think the interaction with --enable-fsckfix is not good: if you --enable-fsckfix, those kernel params are ignored.

i think it would be much less surprising and useful if --enable-fsckfix didn't take all choice away,

ie. if --enable-fsckfix only changed the defaults for the new fsck_mode and fsck_repair variables (~line 65 of conf.c) , and 
if the fsck invocation in line 259 of finit.c simply used whatever the current mode/repair variables are. 

that way a repackager & distributor of finit can pick either an agressive default (--enable-fsckfix) or not, but all is not lost
for the end users.

**Comment by troglobit** [comment]
Good idea. The configure option was added by an external contributor, who also added `--enable-fastboot` support.  So we should take the time to fix that too along the same lines.
