### ISSUE TITLE
service environment variables are not expanded when sourced

### ISSUE THREAD

**Issue by az143** [troglobit/finit#377]
when setting up an `/etc/default/somesvc`, it is currently not possible to reference  variables defined earlier, because 
source_env() only strips undesirable bits before calling setenv().

for example, this construction doesn't work:
```
RUNDIR=/var/run/somesvc
DAEMON_ARGS=--workdir $RUNDIR --other-args...
```
i think that running wordexp() before the setenv() calls would remove this limitation; if that's not true, 
then the limitation should be mentioned in doc/config.md and man/finit.conf.5.

**Comment by az143** [comment]
see pr #379

**Comment by troglobit** [comment]
A `wordexp()` of the value (in key=value) is probably the way to go here.  It fits with the principle of least surprise, does not leak to other processes, and would also keep the documentation to a minimum.
