### ISSUE TITLE
Decouple libuev from finit, add option to link dynamically

### ISSUE THREAD

**Issue by karasz** [troglobit/finit#4]
Please think about the posibility of decoupling libuev from finit so finit could be compiled with a previously installed libuev. Don't you think that would be beneficial for both projects?

Thx

**Comment by troglobit** [comment]
Maybe, libuev is extremely small. But you're right, no point in bloating the system with code duplication!

I'll look into it for the next release. Working on the upcoming integrated inetd support right now :)

**Comment by troglobit** [comment]
I'm postponing this for later.

The overhead for supporting this is not worth the gain atm.  The libuev .so file is 10k stripped, but finit links to the .a archive and does not use timers atm, so the resulting overhead is << 10k.

If anyone sends a patch or pull request I'm willing to reconsider. In the meantime I'll spend the time on getting actual features in.

Also, in any event I'd like to start by decoupling libite (-lite) from Finit. It has many features I'd like to use in other projects as well. Actually, the latest version of BSD queue.h could be part of the libite distribution.  That's far better spent time in my opinion.

**Comment by troglobit** [comment]
Fixed in GIT commit 6531b2f for upcoming v2.0 release.
