### ISSUE TITLE
Eudev: Coldplug and settle

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#49]
As title: https://github.com/troglobit/finit/commit/8f05b36551bbbf3331d8b2a2a0625b8f2d66b7b1#commitcomment-19894579

**Comment by troglobit** [comment]
This could be a good place to gather information and links to experiences with both udev and eudev.  I think it's great that you're using Finit and trying it out with udev and eudev! :smiley: 

Unfortunately, my primary use-case for Finit is embedded, with BusyBox and thus mdev. At least for the moment, so I wont be able to test and help out as much as I'd like.  There are some thoughts about moving to Alpine Linux "soonish", which could be beneficial to this issue, but not in the near future.

However, as usual I'm more than happy to discuss fixes and pull requests with fixes and/or extensions to support other systems.

**Comment by xhebox** [comment]
@troglobit is there a function in finit that run commands sync(not async or fork)? I think i get the point, udevd is running while mounting, so....

**Comment by troglobit** [comment]
Yup, there's `run` ... it's like `task` but runs in sequence in the given runlevel.  So try something like this:

    service [S] /path/to/daemon1 ... 
    run [S] /path/to/cmd --some-args -- Some description of what cmd does
    # Service will not be started until cmd has completed.
    service [S12345] /path/to/daemon2 -- Description

At boot, runlevel [S]`, this example starts `daemon1` in the background and then waits for `cmd` to complete before proceeding to fork off `daemon2`.  Hopefully this does what you want.

**Comment by xhebox** [comment]
@troglobit Oh...my god...you should not move bootclean to bootmisc, since it will clean udev!

**Comment by troglobit** [comment]
Actually, /var/run (or /run) should be clean on boot.  But what you're saying is that there is a dependency on udev/eudev to run *after* bootclean?

I'm thinking maybe it's time to move that part of the boot to a plugin and properly delare that plugin to depend on bootmisc.so.  That way the udev files would not be removed.

Good catch!

**Comment by troglobit** [comment]
OK, I've looked at how SysV init in Debian does this.

1) In mountall, which runs very early, they mark tmpfs file systems like /run with a flag, /run/.tmpfs
2) In bootclean, which runs before bootmisc, they check for $DIR/.tmpfs before cleaning out files

How do you set up /var/run or /run?  In Finit I have added builtin support for creating /run as a tmpfs, with /var/run symlink created in bootmisc.  Maybe you are using something else?

My idea right now is to skip all mount points listed in `bootclean()` which we can identify as `tmpfs` using `/proc/mounts`.

**Comment by troglobit** [comment]
@xhebox I hope these two fixes resolve your issue.  If not, feel free to reopen it or file a new issue.

**Comment by xhebox** [comment]
@troglobit I cant reopen the issue you closed...

And this is not working. You need to find which file the symbolic refers to, this check the link file /var/run  but miss the real dir /run.

**Comment by troglobit** [comment]
Ah, thanks. Didn't know I was the only one allowed to reopen issues.

OK, you're obviously correct, sorry! I'll improve the check.

**Comment by troglobit** [comment]
Hopefully current master, as of 47060c9, works better ...

**Comment by xhebox** [comment]
@troglobit Not working, you need to use lstat, since stat will resolve the symbolic automatically. And strip the '/' from the end of path. Check [the man](http://man7.org/linux/man-pages/man2/readlink.2.html). But forget it, i think this way better:
```
--- bootmisc.c	2016-11-21 13:29:55.725183408 +0000
+++ b/plugins/bootmisc.c	2016-11-21 13:29:55.725183408 +0000
@@ -32,33 +32,15 @@
 #include "../plugin.h"
 #include "../utmp-api.h"
 
-/* Resolve symbolic links */
-static char *desym(char *dir)
-{
-	static char path[80];	/* Should be enough for our use-case */
-	struct stat st;
-
-	if (stat(dir, &st))
-		return NULL;
-
-	if (S_ISLNK(st.st_mode)) {
-		if (-1 == readlink(dir, path, sizeof(path)))
-			return NULL;
-
-		return desym(path);
-	}
-
-	return dir;
-}
-
-static int is_tmpfs(char *dir)
+static int is_tmpfs(char *path)
 {
 	int tmpfs = 0;
 	FILE *fp;
 	struct mntent *mnt;
+	static char dir[80];	/* Should be enough for our use-case */
 
 	/* If /var/run is a symlink, check what it resolves to */
-	dir = desym(dir);
+	realpath(path, dir);
 	if (!dir)
 		return 0;	/* Outlook not so good */
 
```
More [there](http://man7.org/linux/man-pages/man3/realpath.3.html).

**Comment by troglobit** [comment]
Ah, `lstat()` of course. Your version looks much cleaner, didn't even know about realpath(), thanks!

**Comment by troglobit** [comment]
Slight variation of your proposal, without hardcoded array, in b9ae4d0.

**Comment by xhebox** [comment]
Tested, nice work!

**Comment by troglobit** [comment]
Thank you for your patience! :relieved:
