### ISSUE TITLE
Add support building finit statically

### ISSUE THREAD

**Issue by therealprologic** [troglobit/finit#5]
Is it possible to build finit statically? I've had a few attempts but I don't think the Makefile(s) currently make this very easy at the moment...

**Comment by troglobit** [comment]
Hmm, don't think so atm. I'll look into it!

**Comment by therealprologic** [comment]
That would be awesome! Id like to use it in a new small distro where all of
the core parts are static binaries.

**Comment by troglobit** [comment]
If I do a quick fix and cut some corners, do you need any of the plugins?

**Comment by therealprologic** [comment]
Can live without the plugins for now :)

**Comment by troglobit** [comment]
Alright then! Will look at it tonight (CET :)

**Comment by therealprologic** [comment]
Alright :) You may want to look at some of the work
a colleague has done to help achieve this too.

See: http://crux.ster.zone/ports/romster/finit-static/


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by troglobit** [comment]
OK. Looks like sth along the lines of what I was thinking of.
It'll probably be very similar to how Dropbear SSH does it :)

**Comment by therealprologic** [comment]
Cool :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by troglobit** [comment]
Btw, aren't you guys down under usually asleep at this time of day? ;-)

**Comment by therealprologic** [comment]
Normally yes :) But yeah what can I say?

Night owl :)

Just finished putting together a set of buidl scripts
to put together this thing I'm bulding!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by troglobit** [comment]
Heh, know the feeling! ;)

**Comment by troglobit** [comment]
As I mention in a74b640, there still remains a few issues to work around before Finit can be built completely standalone.

    $ make clean all STATIC=1
    LINK    finit
    helpers.o: In function `getgroup':
    helpers.c:(.text+0x10a7): warning: Using 'getgrnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    helpers.o: In function `getuser':
    helpers.c:(.text+0x108e): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    inetd.o: In function `getent':
    inetd.c:(.text+0x127): warning: Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    inetd.c:(.text+0xce): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

The problem is the NSS plugins and similar issues that prevent static linking when using the above functions.  I belive this can be fixed by 1) changing the [@USR:GRP] syntax to allow numeric `uid` and `gid` and simply `ifdef` out the `getgrnam()` and `getpwnam()` calls.

For the inetd support this is slightly worse, the easy way out is to disable inetd support altogether when building statically, but I think that's a bit too extreme.

Comments, suggestions?

**Comment by therealprologic** [comment]
Unfortunately I wouldn't call myself an expert here. But I can live without inetd because the overall goals of my little distro is to serve as a minimal core. I expect users to install an inetd themselves if that's how they want to run services.

**Comment by therealromster** [comment]
Hi troglobit, Yeah prologic and myself (Romster), (seems both names been taken these are our freenode names, hence 'the' prefix.).

As you can see I knocked up a crude way to compile static but the plugins are another story needing dlopen. I'm not much of a programmer but I do dabble a little and have done a fair bit in tool chains and package a lot of ports in crux linux http://crux.nu

I did find this http://stackoverflow.com/questions/14289488/use-dlsym-on-a-static-binary and was thinking of an #ifdef STATIIC in the source code and Makefile. Could even make a list of PLUGINS variable to use for static linking and update those that are easy to compile in.

**Comment by troglobit** [comment]
I think I've actually taken care of the plugins, they're built statically into finit when make is given the `STATIC=1`argument (above). See the top level Makefile if you want to patch them out, or just want to build a few.

The remaining issues, as it seems, is when Finit use functions in GLIBC that are built on top of ... yeah GLIBC-plugins.  I haven't tried to build this yet with another C-library, like musl och uClibc, but I imagine at least uClibc will not give the above warnings.

To what extent do you need Finit to be static?  We could have libuev, libite and the plugins built statically, but maybe you can live with Finit having a dependency on there being a versioned .so file for GLIBC?  If you clone the Finit git repo you'll notice that the resulting binary is quite huge (apx. 1 MiB!)

Cheers!

**Comment by troglobit** [comment]
@therealprologic Btw, I've written a [blog post](http://troglobit.com/blog/2015/03/06/inetd-support-in-finit-v1-dot-12/) on the new inetd in Finit, with poor man's tcpwrappers support, which I think is pretty neat.

**Comment by therealprologic** [comment]
With your patch I believe I have a successful static build. I'm about to test it out in fact. To what extend do I need it to be static? Well I had no plans on shipping a general purpose libc at all on the core system. As an end-user you would install one out of necessity as a dependency on some other app.

So since there's no libc, compiler or toolchain for that matter
that means Kernel + Busybos + Finit all statically compiled and some kind of package manager to install additional software.

Makes sense?

**Comment by therealprologic** [comment]
Cool :) I think it's pretty neat too! I just don't see myself using it. I've often found myself (*personally*) preferring the performance of a proper daemon with good I/O handling than some single-threaded socket server spawned by inetd on demand. But that's just me :)

**Comment by therealprologic** [comment]
Btw are you on IRC at all? I may want to go through some of this with you while trying to adapt finit to my needs :) I just had my first boot attempt (http://i.imgur.com/I3tQhzz.png) and what a miserable failure on my part (*I assume*) :)

**Comment by troglobit** [comment]
Ah, completely static base. Sure, I guess that could make sense in some situations.

Well, the built-in inetd is just an add-on for really small embedded systems. The more I think about it, it should be an optional feature in finit, possible to build without.

No, I'm only on a few private IRC networks (also I'm going away for the weekend, unfortunately).  If you need hints on how to setup the system, and configure the kernel, take a look at [TroglOS](https://github.com/troglobit/troglos), which I've started recently to be a demo of most of my projects.

For other tips and troubleshooting, take a look at the Finit source code. It's really not rocket science, [`finit.c:main()`](https://github.com/troglobit/finit/blob/master/finit.c#L143) is basically what you want to peek at.  For instance, there the following comment can be found `... kernel is assumed to run devtmpfs for /dev` :)

Good Luck! /J

**Comment by therealprologic** [comment]
No problems :) Have a nice weekend away.

Just nutting through some issues right now.

Apparently I don't have a /dev/urandom :)

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by therealprologic** [comment]
One thing I don't get right now is why
finit is trying to start /sbin/udevd which
doesn't exist in a busybox system.

I don't see/find any references to this
in any of the finit source code.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by troglobit** [comment]
Did you find the problem?  Finit defaults to udevd unless you define `EMBEDDED_SYSTEM` in your environment.  Like so https://github.com/troglobit/troglos/blob/master/packages/finit/Makefile#L27

This check is in `finit.h`, I should document this better!

**Comment by therealprologic** [comment]
Yes I figured this out after grepping the codebase a bit :)

Shouldn't/Couldn't this be a configurable option in ``/etc/finit.conf``?

**Comment by troglobit** [comment]
Good! :)

Yep, it really should! *adding to TODO list*

**Comment by therealprologic** [comment]
Excellent :)

Can we add disabling inetd to teh TODO as well?
(I could file an Issue)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by troglobit** [comment]
Sure thing, yes please do that!

**Comment by troglobit** [comment]
Hmm, the udev/mdev soup currently seems to need to run *before* parsing finit.conf ... stupid legacy. Appears to be due to fsck running from inside the conf-parser ... I'll add an issue for this so I can refactor that stuff.

**Comment by therealprologic** [comment]
Ahh right.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by troglobit** [comment]
With the latest configure script on master there is a `--enable-static` that now creates
a build that does not complain anymore.

Please note, I've not tested it at all, and the drop-privs support has been disabled,
since it relied on `getpwnam()` (see above GLIBC linking issues).

Hope this helps!

**Comment by therealprologic** [comment]
Cool :)

**Comment by troglobit** [comment]
Fixed, closing.
