### ISSUE TITLE
After --enable-watchdog, reboot -p rebooted my pc instead of down

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#54]
Hmm...Without this option, works normally. Have no ideas about whether it's my specific problem(musl, or my configs). Or it's indeed a bug of finit. I'll take a look tomorrow, time to bed... I'll close the issue if it's on my own or post a patch. Also, you can do it yourself if you cloud see this while i'm sleeping. :smile:

**Comment by troglobit** [comment]
Good catch, and obvious miss due to my focus on (my type of) embedded systems (that don't allow power-off/halt) fixing!

**Comment by xhebox** [comment]
Nice work!
