### ISSUE TITLE
getty: finit hangs when a getty is setup on a non-existing tty

### ISSUE THREAD

**Issue by wkz** [troglobit/finit#56]
A config line like:

    tty [12345] /dev/ttyS0   115200 vt100

On a system with no `ttyS0` (device node may be present, but no real device backing it), causes `finit` to hang, endlessly spawning new `getty` children.

**Comment by troglobit** [comment]
Ouch, good catch! Any insight into what may be a useful patch?

**Comment by wkz** [comment]
Unfortunately not yet. I just stumbled across it when bringing up some new hardware and thought I would just log it as an issue so that we won't forget it.

**Comment by troglobit** [comment]
Here's a proposal, using `tcgetattr()` to check if the TTY is "live" https://github.com/troglobit/toolbox/blob/master/checktty.c

We should, however, probably have a way of handling plugging in a serial console at runtime ...

**Comment by troglobit** [comment]
Hopefully 88039f3 fixes the issue, or at least mitigates it. If not, please reopen! 

Merry Christmas! :santa:
