### ISSUE TITLE
Make inetd optional

### ISSUE THREAD

**Issue by therealprologic** [troglobit/finit#6]
In my case I don't see myself using inetd in the system/distro I'm building.

Let's make it a compile time optional feature :)

**Comment by troglobit** [comment]
Started looking into this ...  I'll likely add a small configure script that can be used to select between a whole slew of things at the same time, not just `--disable-inetd` :)

More of that tomorrow though, must catch some sleep before work!

**Comment by therealprologic** [comment]
No problems! Would that include a ``--disable-plugins`` as well? I remember you saying plugins won't really work with a statically built finit?

**Comment by troglobit** [comment]
I'm not so sure about that. I think the plugins should work now ... with STATIC=1 they are built-in.  However, there will be a `--with-plugins="list of plugins"` :)

... and an `--enable-static` as well!

**Comment by therealprologic** [comment]
Beautiful :) Love it :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by troglobit** [comment]
Current master now has a configure script with some goodies. Hope this helps!

**Comment by therealprologic** [comment]
I'll try this out now :)

**Comment by troglobit** [comment]
Fixed, closing.
