### ISSUE TITLE
initctl ignores nonexistent services

### ISSUE THREAD

**Issue by reverendhomer** [troglobit/finit#60]
Hi,
while digging in finit and troglos, I found that `initctl start/stop any_nonexistent_service_name` just exits without any error:
```
~ # initctl start nonexistent-service
~ # echo $?
0
```

I don't think it is a good idea. Do you have any plans to add some warnings and make initctl return non-zero exit code in such situation?

**Comment by troglobit** [comment]
Haven't really thought about it, but it's a great idea, thanks! 

I'll see what I can do before the v3 release 👍
