### ISSUE TITLE
fsck: sometime fsck is done by initramfs, add a 'en/disable' switch for fsck checking?

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#64]
as title

**Comment by troglobit** [comment]
True, but then the initramfs also has mounted the filesystem as well, right?

Maybe it would be sufficient to just add a check `is_mounted()` before attempting `fsck()`?

**Comment by xhebox** [comment]
If I understand right, `is_mount()` before `fsck()` means to check if `/dev/sdX` is mounted? That should be enough.

**Comment by troglobit** [comment]
Yep, that's what I meant. Sorry, it's still early hours here in Sweden :-)

OK, I'll look into it!

**Comment by troglobit** [comment]
There, should work :-)

**Comment by xhebox** [comment]
Tested
