### ISSUE TITLE
"init" symlink is created in usr/sbin/ instead of sbin/

### ISSUE THREAD

**Issue by reverendhomer** [troglobit/finit#67]
Subj on version 3.0-rc2. Can you fix it, please?

**Comment by troglobit** [comment]
Hmm, odd ... should be controlled by --prefix, but you're right the defaults should be sane. I'll look into it, thanks!

**Comment by reverendhomer** [comment]
I got this issue while adding finit package to the buildroot, if this info can help you somehow. And I build it via simpe `$(eval $(autotools-package))`

**Comment by troglobit** [comment]
Aha, well that's for general packages I guess. Do they have any init packages, other than systemd, that use autoconf?

Anyway, I think it can be fixed by tweaking the GNU defaults a bit. I'll look at it tonight, CET.

**Comment by troglobit** [comment]
OK, I've looked into this now and it must be Buildroot overriding the Finit `configure` defaults.
I have explicitly added the following to `configure.ac`:

    # Change default prefix, we're PID 1 after all ...
    AC_PREFIX_DEFAULT([])

So if you run `configure` without any arguments it does the right thing:

``` sh
./configure
make clean; make -j5
DESTDIR=/tmp/staging make install
    ...
tree /tmp/staging
 ~/Troglobit/finit  ⑂ master +  $  tree /tmp/staging
/tmp/staging
├── include
│   └── finit
│       ├── cond.h
│       ├── finit.h
│       ├── helpers.h
│       ├── inetd.h
│       ├── plugin.h
│       └── svc.h
├── lib
│   └── finit
│       └── plugins
│           ├── bootmisc.so
│           ├── hwclock.so
│           ├── initctl.so
│           ├── netlink.so
│           ├── pidfile.so
│           ├── procps.so
│           ├── tty.so
│           └── urandom.so
├── sbin
│   ├── finit
│   ├── halt -> reboot
│   ├── init -> finit
│   ├── initctl
│   ├── poweroff -> reboot
│   ├── reboot
│   ├── service
│   ├── shutdown -> reboot
│   ├── suspend -> reboot
│   └── telinit -> finit
└── share
    └── doc
        └── finit
            ├── finit.conf
            ├── LICENSE
            └── README.md

```

The `DESTDIR` trick is used by, e.g. Debian/RedHat, when creating packages. Useful to verify the
resulting root of a package.

Anyway, not sure I can help more than this. Terrybly sorry, but you have to check with Buildroot how to tell their build scripts to not change `--prefix`.

**Comment by troglobit** [comment]
@reverendhomer Any comments, or can we close this issue?

**Comment by reverendhomer** [comment]
Sorry for the delay, I could not recheck it and haven't solved it yet, but I agree that this is not a finit issue. Thanks for your support! :)

**Comment by troglobit** [comment]
@reverendhomer No problem mate, good luck! :)
