### ISSUE TITLE
built-in getty does not ask for password

### ISSUE THREAD

**Issue by reverendhomer** [troglobit/finit#68]
Hi!

I have built buildroot with finit. And I have an issue that built-in getty does not ask for password in serial console. If I remove all mentions of `tty` in `/etc/finit.conf`, getty keeps starting.

Also, I was looking for a way to avoid using built-in getty and use busybox getty instead. I've found `--enable-embedded` option in [build.md](https://github.com/troglobit/finit/blob/dd566acfd2b8f182ec1a930c979843072e4b2564/doc/build.md#L25) but looks like it does not exist anymore. Can you please at least remove it from the docs?

**Comment by troglobit** [comment]
The built-in getty (or any getty for that matter) only only asks for login: and then hands over to `/bin/login` which gives the password prompt and checks against PAM, `/etc/passwd` or `/etc/shadow`.

Hmm, I need to look into that ... it should definitely be possible to use Finit w/o the built-in getty and instead set up a `service ... /bin/getty`.  Thank you for bringing this up, will look into this during the weekend, I'll be working on TroglOS anyway to finalize Finit3 testing before release.

Ah, the docs, yup updated!

**Comment by reverendhomer** [comment]
>The built-in getty (or any getty for that matter) only only asks for login: and then hands over to /bin/login which gives the password prompt and checks against PAM, /etc/passwd or /etc/shadow.

Hmm, strange. It does not ask for login neither.

>Ah, the docs, yup updated!

Thank you! :)

**Comment by troglobit** [comment]
Sorry mate, just cannot reproduce this in my own BusyBox-based setup :disappointed:

**Comment by reverendhomer** [comment]
Okay, I will check my configuration, thanks for feedback!
