### ISSUE TITLE
add a way to use log_silent or not

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#75]
long time no see, :)

I've updated to the latest finit now, and found all the log has gone due to log_silent(). log_silent() may be good when you have a stable environment, but when not, i need those logs to know what happened. It should not only be available when you compile it in debug, not so convenient. Especially i thought i was in a stable env, but i just failed to boot and i dont know what happened.

some idea:
1. add a flag in finit.conf
2. maybe check /proc/cmdline for quiet and use it as a flag for finit

**Comment by troglobit** [comment]
I've only changed the default to be silent.  You can enable the old-style bootup with `./configure --enable-progress` and there is still the possibility of enabling debug on the kernel command line with `--debug`.

In your case with an unstable env I'd recommend adding `--debug` to the kernel command line.

**Comment by troglobit** [comment]
I guess I should update the docs, or perhaps compose a `doc/debug.md`, to explain the different log options.  Sorry for the confusion!

Below are some notes for my own benefit:
- The `--disable-quiet` configure option and parsing of kernel cmdline `quiet` was removed in 516dbcc
- In e46e3cd a bit more is explained in the commit message

**Comment by xhebox** [comment]
ah, thanks for your explanation, i guess i can close the issue. Look forward to your new actions on docs. :)
