### ISSUE TITLE
Remove old startx and username .conf directives

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#77]
**Original subject:** respect user configurations in passwd, allow Xorg.wrap to start as non-root by default

I recently set finit to startx, i met two points, where i think we should do sth.  (copied from #76)

1. USER and SHELL env vars when start service: It's not a login shell, so finit invoked /bin/sh(dash) rather than /bin/bash which is configured to the default one. I am think about if it's better to set SHELL, not only to respect user configuration, but also respect the configuration like setting shell to /bin/nologin to prevent possible attacks. And i have learned that USER was also provided, better compatibility, not so bad.

2. startx is an alias to service, so it's not a login shell, in another word, it's not a console. Xorg.wrap defaults only to allow console users to non-root-start. It's absolutely a good idea to make it console instead set 'allow_users = anybody` in config file. But, i dont know if it's possible.

**Comment by troglobit** [comment]
I will make an attempt to look at this with an Alpine Linux install I have.  Need to test this myself first to see if I understand the problems correctly, was a while since I tried running X from Finit.

**Comment by xhebox** [comment]
@troglobit agree on removing :)

**Comment by troglobit** [comment]
Thanks!  I'll remove it later today :)
