### ISSUE TITLE
External getty does not support agetty syntax

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#78]
sorry, i am already in my bed. In short, agetty ask for ttyX instead of /dev/ttyX. finit told me it didn't find device, any plan on supporting agetty? though your builtin one is enough for me, just let you know. gotta sleep, see you..

**Comment by troglobit** [comment]
Hmmm, was afraid of that. Only tried BusyBox getty and of course agetty is too stupid to handle an absolute path ... 😒

I'll see what I can do, thanks for the heads up!

**Comment by troglobit** [comment]
Have a refactored parser in progress now.
