### ISSUE TITLE
dbus-daemon crashes

### ISSUE THREAD

**Issue by aifoslinux** [troglobit/finit#83]
I'm having issues with dbus-daemon ever since the dbus plugin became a service during booting. I've tested with the latest commit b45c3d5, but the issue persists. I have  reverted to commit 6818813 and dbus loads fine and subsequently making elogind work as intended as well.

I've been busy preparing a livecd[1] in case you want to install it into qemu image and experiment with the odd behaviour. 

1: https://sourceforge.net/projects/aifos/files/isos/aifoslinux-supra-2017.10.28.iso

Edit: I don't seem to have the issue on real hardware now, and I don't know how I fixed it. But the issue remains on qemu.

**Comment by troglobit** [comment]
Hi, awesome of you to create the ISO helped a lot to track down the issue! :+1: 

```
-sh-4.4# which dbus-daemon
/bin/dbus-daemon

-sh-4.4# initctl status -v
...
6   crashed 0  [S12345----] /bin/dbus-daemon --nofork --system

-sh-4.4# /bin/dbus-daemon --nofork --system
Unknown username "pulse" in message bus configuration file
Failed to start message bus: Could not get UID and GID for username "dbus"
```

If I create a system group and system user `dbus` (and remove `/run/dbus.pid`) I can restart the dbus-daemon using:

```
groupadd -r dbus
useradd -r -g dbus dbus 
initctl start dbus-daemon
```

Hope this helps! :smiley:

**Comment by aifoslinux** [comment]
Hello, thank you for solving this issue for me :) It was the packaging issue rather than finit related issue. It was the preinstall script that didn't run inside the chroot as it should have, so I've fixed it. Everything works as expected now.

It's a pleasure to use finit :)

**Comment by troglobit** [comment]
No problem, glad to help! :smiley:
