### ISSUE TITLE
rc.local

### ISSUE THREAD

**Issue by aifoslinux** [troglobit/finit#92]
Since 3.1-rc  /etc/rc.local isn't run correctly anymore. My rc.local script contains:
```
#!/bin/sh

rmmod snd_hda_intel
modprobe snd_hda_intel
```
The script is executed with version 3.0 and I have working sound. With 3.1-rc device nodes in /dev/snd have wrong permissions. eudev doesn't create nodes properly I guess.

**Comment by troglobit** [comment]
I just tested with the latest commit on the master branch, so possibly fixed since -rc1. Sorry for that, will have -rc2 out soon!

**Comment by aifoslinux** [comment]
Later commits than commit bbaa7a1 show /dev/snd without +, ie:
```
drwxr-xr-x  2 root root       60 Dec 28 17:42 by-path
crw-------  1 root root  116, 10 Dec 28 17:42 controlC0
crw-rw---- 1 root root  116,  2 Dec 28 17:42 controlC1
crw-------  1 root root  116, 15 Dec 28 17:42 hwC0D0
crw-------  1 root root  116,  9 Dec 28 17:42 hwC1D0
crw-------  1 root root  116, 12 Dec 28 17:42 pcmC0D0c
crw-------  1 root root  116, 11 Dec 28 17:42 pcmC0D0p
crw-------  1 root root  116, 13 Dec 28 17:42 pcmC0D1p
crw-------  1 root root  116, 14 Dec 28 17:42 pcmC0D2c
crw-rw---- 1 root root  116,  7 Dec 28 17:42 pcmC1D10p
crw-------  1 root root  116,  8 Dec 28 17:42 pcmC1D11p
crw-rw---- 1 root root  116,  3 Dec 28 17:42 pcmC1D3p
crw-rw---- 1 root root  116,  4 Dec 28 17:42 pcmC1D7p
crw-rw---- 1 root root  116,  5 Dec 28 17:42 pcmC1D8p
crw-rw---- 1 root root  116,  6 Dec 28 17:42 pcmC1D9p
crw-rw----+ 1 root audio 116, 33 Dec 28 17:42 timer
```
Earlier commits than commit bbaa7a1 show:
```
drwxr-xr-x  2 root root       60 Dec 28 17:42 by-path
crw-------  1 root root  116, 10 Dec 28 17:42 controlC0
crw-rw----+ 1 root root  116,  2 Dec 28 17:42 controlC1
crw-------  1 root root  116, 15 Dec 28 17:42 hwC0D0
crw-------  1 root root  116,  9 Dec 28 17:42 hwC1D0
crw-------  1 root root  116, 12 Dec 28 17:42 pcmC0D0c
crw-------  1 root root  116, 11 Dec 28 17:42 pcmC0D0p
crw-------  1 root root  116, 13 Dec 28 17:42 pcmC0D1p
crw-------  1 root root  116, 14 Dec 28 17:42 pcmC0D2c
crw-rw----+ 1 root root  116,  7 Dec 28 17:42 pcmC1D10p
crw-------  1 root root  116,  8 Dec 28 17:42 pcmC1D11p
crw-rw----+ 1 root root  116,  3 Dec 28 17:42 pcmC1D3p
crw-rw----+ 1 root root  116,  4 Dec 28 17:42 pcmC1D7p
crw-rw----+ 1 root root  116,  5 Dec 28 17:42 pcmC1D8p
crw-rw----+ 1 root root  116,  6 Dec 28 17:42 pcmC1D9p
crw-rw----+ 1 root audio 116, 33 Dec 28 17:42 timer
```
The audio group is replaced with root after finit 3.0. I'll check witch commit started it.

**Comment by aifoslinux** [comment]
Commit fcdb5c2 shows audio group:
```
drwxr-xr-x  2 root root       60 Dec 28 17:54 by-path
crw-rw----+ 1 root audio 116, 10 Dec 28 17:54 controlC0
crw-------  1 root root  116,  2 Dec 28 17:54 controlC1
crw-rw----+ 1 root audio 116, 15 Dec 28 17:54 hwC0D0
crw-------  1 root root  116,  9 Dec 28 17:54 hwC1D0
crw-rw----+ 1 root audio 116, 12 Dec 28 17:54 pcmC0D0c
crw-rw----+ 1 root audio 116, 11 Dec 28 17:54 pcmC0D0p
crw-rw----+ 1 root audio 116, 13 Dec 28 17:54 pcmC0D1p
crw-rw----+ 1 root audio 116, 14 Dec 28 17:54 pcmC0D2c
crw-------  1 root root  116,  7 Dec 28 17:54 pcmC1D10p
crw-------  1 root root  116,  8 Dec 28 17:54 pcmC1D11p
crw-------  1 root root  116,  3 Dec 28 17:54 pcmC1D3p
crw-------  1 root root  116,  4 Dec 28 17:54 pcmC1D7p
crw-------  1 root root  116,  5 Dec 28 17:54 pcmC1D8p
crw-------  1 root root  116,  6 Dec 28 17:54 pcmC1D9p
crw-rw----+ 1 root audio 116, 33 Dec 28 17:54 timer
```

**Comment by troglobit** [comment]
I see, OK, I'll have a look at it. Thank you for pointing this out!

**Comment by aifoslinux** [comment]
I use finit on musl based x86_64 platform. Musl libc seems to have different approach to rlimit compared to glibc.

**Comment by troglobit** [comment]
Ah, thanks for reminding me, I've managed to reproduce your problem now in my Alpine Linux setup. :+1: 

Finit says it runs /etc/rc.local, but the contents of the script has not actually run. So seems to be your exact problem. I've only refactored the rlimit support, so unless one has rlimit config in /etc/finit.d/*.conf everything *should* work as it did in 3.0 ... but evidently not.

I'll look into this, and some other issues I've found, in detail over the coming days.

**Comment by troglobit** [comment]
This is odd. I've retested with the latest master on my Alpine install, it too is x86_64 with musl, and it works fine for me. To verify that /etc/rc.local runs I have the following contents:

```
#!/bin/sh

echo "rc.local has run" >/tmp/hello.local
```

(I thought I had reproduced your problem first, but it turned out to be a simple user error by me, bad path in redirect above.)

I've also verified that rlimits are set similarly between musl and glibc. Only thing missing from musl seems to be `rttime`, but that doesn't affect regular processes. So currently I'm at a loss as to why it doesn't work for you. :disappointed: 

Are you sure rc.local doesn't run, maybe there's something else that's wrong?

**Comment by aifoslinux** [comment]
I think rc.local is running but I have no idea why there is permission issue.  I'll try out booting with a livecd and see if my system is not affected with some kind of bug.

**Comment by aifoslinux** [comment]
I've tested finit based on commit b68c5c1 through livecd and it was the same as my system, the parmissions are wrong there too. I got this error message when I was running 'modprobe snd_hda_intel':

> finit[1:] Device event manager daemon keeps crashing, not restarting

I'll try finit with commit 44007c8 on livecd and see if it works as it does on my system.

**Comment by troglobit** [comment]
Sounds like eudev is crashing, for some reason, is there anything shown in the log files?  Finit tries to restart the service 10 times before giving up and printing the above error message. If eudev doesn't run then that likely explains why the permissions are wrong.

**Comment by aifoslinux** [comment]
Well I tried with commit 44007c8 and I didn't get any finit error on livecd and permissions where fine. I guess there is something that keeps eudev not working after this commit. I wonder why.

**Comment by troglobit** [comment]
I'm pretty sure I found it!  The `global_rlimit[]` was not initialized at the time the `udevd` service was registered, leading to unpredicatable rlimits being set, which likely led to it crashing.

Terribly sorry it took this long to track this regression down, thank you so much for your patience!

Please let me know if you still experience problems, in which case we'll reopen the issue.

**Comment by aifoslinux** [comment]
Awesome!! I'm really glad that you found the missing piece :) I'll try the recent commit and report back!

**Comment by aifoslinux** [comment]
The latest commit solved the issue and I'm happy to have sound again :) Thanks for the good work!

**Comment by troglobit** [comment]
@aifoslinux That is truly excellent news, thank you! :relieved: :v:
