### ISSUE TITLE
How to set runtime dependable ARGS for a SERVICE

### ISSUE THREAD

**Issue by joerg-krause** [troglobit/finit#93]
I am trying to port SysV-based BusyBox init start-stop-scripts to Finit, e.g. something like this:

```
DEVICENAME=$(cat /etc/devicename)

case "$1" in
start) start-stop-daemon -S /usr/bin/upmpdcli -f "$DEVICENAME"
...
```

My problem is how to set the run-time ARGS when using it as a service:

```
service /usr/bin/upmpdcli ARGS
```

I know, I can use a task to start a shell-script which start the service, but then I cannot control the service using initctl, right?

**Comment by troglobit** [comment]
A service stanza like this should work (stolen from the upstream systemd unit file):

    service [2345] /usr/bin/upmpdcli -c /etc/upmpdcli.conf -- UPnP Renderer front-end to MPD

and no, if you start a service as a task + start-stop-daemon it will not be possible to control with initctl.

**Comment by joerg-krause** [comment]
The upmpdcli service was just an example. There are programs which do not read a config file, but only get their arguments via the command line. Is there a way to pass an argument read from a file to the service stanza?

If a make a shell script, which does call the program directly, e.g in `/etc/start.d/program`.

``` sh
DEVICENAME=$(cat /etc/devicename)
/usr/bin/program -f "$DEVICENAME"
```

... and make it a task:

```
task /etc/start.d/program -- Example Program
```

... it will not be possible to control it with initctl either, right?

**Comment by troglobit** [comment]
Aha, now I get what you're after. No, there is no such mechanism at the moment in Finit. Separate start script + command line configuration file is not directly translatable to Finit style .conf files, sorry.

One of the reasons for this is the built-in dependency control system, which can track changes to files in /etc/finit.d/*.conf and /run/*.pid to determine when to start or restart dependant services. The idea is to instead keep the configuration in the /etc/finit.d/service.conf file, modify or just touch the file, and issue an `initctl reload` to have Finit automatically stop/start/restart updated services, and their dependencies.

I guess you could have a starter script, or wrapper, like you describe. As long as it remains in the foreground so Finit can track its PID.  If that wrapper in turn responds to SIGTERM (and SIGHUP  if you want), propagating those signals to the underlying service, then it should work. But that's maybe a bit too clumsy.

**Comment by joerg-krause** [comment]
Thanks for the input! Following [this](http://veithen.github.io/2014/11/16/sigterm-propagation.html) blog, I've written a wrapper shell script:

```
do_set_options { ... }
do_set_options

trap 'kill -s TERM $PID' SIGTERM
$DAEMON $OPTIONS &
PID=$!
wait $PID
trap - SIGTERM
wait $PID
EXIT_STATUS=$?
```

Now, I can control the service using initctl. What do you think?

**Comment by troglobit** [comment]
Looks ... magical! :smiley: :+1: 

Make sure to declare the service in `/etc/finit.d/*.conf` with `<!>` to denote that it doesn't support SIGHUP, unless you add that too to the wrapper script.  That way Finit will stop/start such a service instead of sending SIGHUP at restart/reload. E.g.

    service [235] <!> /etc/start.d/program -- Example Program

(The default set of runlevels is `[234]`, I'm just explicitly providing an example here as a reminder.)

**Comment by troglobit** [comment]
Now, this discussion seems to have started a background process in my brain. Maybe it wouldn't bee too hard to add support for your shell-script-like variables, like `DEVICENAME=$(cat /etc/devicename)` and `$DEVICENAME` ...

We have something similar in libConfuse, which I've considered adopting for Finit, but I hadn't planned for it until perhaps Finit v4.  But really, how hard could it possibly be to graft the libConfuse variable handling onto Finit .conf files?  I've already reserved '$' for this future purpose long ago ... (I guess as long as I document the caveat that it would wreck the condition handling)

**Comment by joerg-krause** [comment]
After reading the blog post again I realized that the "magical" script is too overblown for my use case. Additionally to running some code to prepare the command line options, it solves the problem with running some clean-up code and handling CTRL^C. Dropping the unnecessary stuff, it's very simple:

```
# Prepare the command line
do_set_options { ... }
do_set_options

exec $DAEMON $OPTIONS
```

I had a quick look at libConfuse. If setting variables would be supported the same way in Finit, it is still necessary to run some pre-shell-script before actually starting the service.

**Comment by troglobit** [comment]
That looks quite a bit cleaner, well done!

Interesting, what does such a pre-shell-script usually do? (Most of the pre-stuff is handled by plugins in Finit, like [plugins/bootmisc.so](https://github.com/troglobit/finit/blob/master/plugins/bootmisc.c).)

**Comment by joerg-krause** [comment]
The pre-stuff handled by the plugins are done while booting. Some command line options for a service might change while running the system, for example they are changed by the user or an external program, e.g. a friendly device name, the audio output device, the network interface, etc. Not all programs support changing these values at runtime, they must be re-started with the new values. The pre-script is responsible to set the corresponding values before starting the service.

**Comment by troglobit** [comment]
I see, so sort of like the systemd `ExecStartPre`, OK.  Well it seems your solution with a wrapper script is turning into quite an elegant solution for cases like these :smiley::+1: 

Just a side note, you mentioned putting scripts like these in `/etc/start.d/`, don't know if you've remapped the default `/etc/finit.d/` (`configure --with-rcsd`) or if you just wanted a place for those scripts. Just wanted to mention that Finit only reads `*.conf` files from `/etc/finit.d`, so you can easily put the wrapper `.sh` scripts there too, if you'd like.

**Comment by joerg-krause** [comment]
Yes, sort of `ExecStartPre`. And yes, I am quite comfortable with the wrapper script as I can nearly reuse my SysV-based start-stop-daemon scripts (namely without start/stop).

I've put the Finit service `*.conf` scripts in `/etc/finit.d/available` and the wrapper shell scripts in `/etc/start.d/`, e.g. (simplified):

```
# cat /etc/finit.d/available/spotify.conf 
service <!,net/route/default> /etc/start.d/spotify -- Spotify

# cat /etc/start.d/spotify
DAEMON=/usr/bin/spotify

do_set_options { ... }
do_set_options

exec $DAEMON $OPTIONS
```

I think it is cleaner to separate the Finit `*.conf` and the start shell scripts. What is the benefit of using `--with-rcsd=/etc/start.d`

**Comment by troglobit** [comment]
Looks great, well done! 

Was just a suggestion, not entirely clear perhaps what files below /etc/finit.d that are used by Finit. Some users may prefer to have everything related to the init daemon in one sub-directory, but the way those wrapper scripts look I see no benefit. Just looks plain awesome :sunglasses:

**Comment by joerg-krause** [comment]
Thanks a lot for all your help and input! Finit is quite awesome!

I'll close this issue as my problem is resolved. Maybe we can add an example to the docs about using a wrapper script when something like systemds `ExecStartPre` is requested?

```
$ cat /etc/finit.d/available/myprogram.conf 
service <!,net/route/default> /etc/start.d/myprogram -- My Program

$ cat /etc/start.d/myprogram

# Prepare the command line options
OPTIONS=...

exec /usr/bin/myprogram $OPTIONS
```

**Comment by troglobit** [comment]
No problem, glad you like it! :smiley: 

Definitely, good idea!  Maybe something for `doc/config.md` ... care to whip up a pull request?
